include:
- file: /r4.1/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-dom0.yml
  project: QubesOS/qubes-continuous-integration
# It includes all the distributions
#- file: /r4.1/gitlab-vm.yml
#  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-vm-fedora.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
# It includes all the distributions
#- file: /r4.2/gitlab-vm.yml
#  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-vm-fedora.yml
  project: QubesOS/qubes-continuous-integration
