include:
- file: /r4.3/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.3/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
# It includes all the distributions
#- file: /r4.3/gitlab-vm.yml
#  project: QubesOS/qubes-continuous-integration
- file: /r4.3/gitlab-vm-fedora.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.3/gitlab-vm-debian.yml
  project: QubesOS/qubes-continuous-integration
